osx_image: xcode10.1
sudo: required
dist: trusty
language: c
matrix:
    include:
        - os: osx
        - os: linux
          env: CC=clang CXX=clang++ npm_config_clang=1
          compiler: clang
cache:
    directories:
        - node_modules
        - app/node_modules
        - '$HOME/.electron'
        - '$HOME/.cache'
addons:
    apt:
        packages:
            - libgnome-keyring-dev
            - icnsutils
before_install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install --no-install-recommends -y icnsutils graphicsmagick xz-utils; fi
install:
    - nvm install 10
    - npm install -g yarn
    - yarn install
script:
    - yarn test
    - yarn build
branches:
    except:
        - "/^v\\d+\\.\\d+\\.\\d+$/"
